name = "algo-trade-hono"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

[vars]
SECRET_KEY = ""
BINGX_API_KEY = ""
BINGX_SECRET_KEY = ""

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "algotrade-db"
database_id = ""

# [triggers]
# crons = [""]
